name: revanced_manager
description: An unofficial ReVanced Manager based on Flutter.
homepage: https://github.com/Aunali321/revanced-manager

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_cache_manager: ^3.3.0
  flutter_svg: ^1.1.1+1
  google_fonts: ^3.0.1
  installed_apps: ^1.3.1
  json_annotation: ^4.6.0

  #networking
  http: ^0.13.4
  dio: ^4.0.6
  github: ^9.4.0

  path_provider: ^2.0.11
  device_apps: ^2.2.0

  #state management
  stacked: ^2.3.15

  #navigation
  stacked_services: ^0.9.3

  #inversion of control
  get_it: ^7.2.0
  injectable: ^1.5.3
  stacked_generator: ^0.7.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
