name: revanced_manager
description: An unofficial ReVanced Manager based on Flutter.
homepage: https://github.com/Aunali321/revanced-manager

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_i18n: ^0.32.4
  flutter_svg: ^1.1.1+1
  get_it: ^7.2.0
  github: ^9.4.0
  google_fonts: ^3.0.1
  http: ^0.13.4
  injectable: ^1.5.3
  installed_apps: ^1.3.1
  json_annotation: ^4.6.0
  path_provider: ^2.0.11
  stacked: ^2.3.15
  stacked_generator: ^0.7.14
  stacked_services: ^0.9.3
  timeago: ^3.2.2

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/i18n/
